syntax = "proto3";
import "feature_state.proto";
import "feature_track.proto";

option csharp_namespace = "OneMoreTaskTracker.Proto.Features.PatchFeatureCommand";
package mr_helper.features;

service FeaturePatcher {
  rpc Patch (PatchFeatureRequest) returns (FeatureDto);
}

message PatchFeatureRequest {
  int32 id = 1;
  int32 caller_user_id = 2;
  optional int32 expected_version = 3;
  optional string title = 4;
  optional string description = 5;
  optional int32 lead_user_id = 6;
  optional string cs_approving_planned_start  = 7;
  optional string cs_approving_planned_end    = 8;
  optional int32  cs_approving_owner_user_id  = 9;
  optional string development_planned_start   = 10;
  optional string development_planned_end     = 11;
  optional int32  development_owner_user_id   = 12;
  optional string testing_planned_start       = 13;
  optional string testing_planned_end         = 14;
  optional int32  testing_owner_user_id       = 15;
  optional string ethalon_testing_planned_start = 16;
  optional string ethalon_testing_planned_end   = 17;
  optional int32  ethalon_testing_owner_user_id = 18;
  optional string live_release_planned_start  = 19;
  optional string live_release_planned_end    = 20;
  optional int32  live_release_owner_user_id  = 21;
}

message FeatureDto {
  int32        id                 = 1;
  string       title              = 2;
  string       description        = 3;
  FeatureState state              = 4;
  string       planned_start      = 5;
  string       planned_end        = 6;
  int32        lead_user_id       = 7;
  int32        manager_user_id    = 8;
  string       created_at         = 9;
  string       updated_at         = 10;
  reserved 11;
  int32        version            = 12;
  repeated     FeatureTrackDto   tracks     = 13;
  string       cs_approving_planned_start    = 14;
  string       cs_approving_planned_end      = 15;
  int32        cs_approving_owner_user_id    = 16;
  string       development_planned_start     = 17;
  string       development_planned_end       = 18;
  int32        development_owner_user_id     = 19;
  string       testing_planned_start         = 20;
  string       testing_planned_end           = 21;
  int32        testing_owner_user_id         = 22;
  string       ethalon_testing_planned_start = 23;
  string       ethalon_testing_planned_end   = 24;
  int32        ethalon_testing_owner_user_id = 25;
  string       live_release_planned_start    = 26;
  string       live_release_planned_end      = 27;
  int32        live_release_owner_user_id    = 28;
}
