// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneMoreTaskTracker.Features.Features.Data;

#nullable disable

namespace OneMoreTaskTracker.Features.Migrations
{
    [DbContext(typeof(FeaturesDbContext))]
    partial class FeaturesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("features")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneMoreTaskTracker.Features.Features.Data.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("LeadUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ManagerUserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("PlannedEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("date");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeadUserId");

                    b.HasIndex("ManagerUserId");

                    b.HasIndex("State");

                    b.ToTable("Features", "features");
                });

            modelBuilder.Entity("OneMoreTaskTracker.Features.Features.Data.FeatureGate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ApproverUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<string>("GateKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<short?>("Track")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("FeatureId", "GateKey")
                        .IsUnique();

                    b.ToTable("FeatureGates", "features");
                });

            modelBuilder.Entity("OneMoreTaskTracker.Features.Features.Data.FeatureSubStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<short>("Ordinal")
                        .HasColumnType("smallint");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<short>("PhaseKind")
                        .HasColumnType("smallint");

                    b.Property<DateOnly?>("PlannedEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("date");

                    b.Property<short>("Track")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("FeatureId", "Track", "PhaseKind");

                    b.HasIndex("FeatureId", "Track", "PhaseKind", "Ordinal")
                        .IsUnique();

                    b.ToTable("FeatureSubStages", "features");
                });

            modelBuilder.Entity("OneMoreTaskTracker.Features.Features.Data.FeatureGate", b =>
                {
                    b.HasOne("OneMoreTaskTracker.Features.Features.Data.Feature", null)
                        .WithMany("Gates")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneMoreTaskTracker.Features.Features.Data.FeatureSubStage", b =>
                {
                    b.HasOne("OneMoreTaskTracker.Features.Features.Data.Feature", null)
                        .WithMany("SubStages")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneMoreTaskTracker.Features.Features.Data.Feature", b =>
                {
                    b.Navigation("Gates");

                    b.Navigation("SubStages");
                });
#pragma warning restore 612, 618
        }
    }
}
